name: Build and save my Docker image to a regitry

on:
  push:
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main

    paths:
          - 'src/backend/**' # pour préciser qu'il fait ces modif que si c'est le backend qui est modifié 

env:
  REG_NAME: "acrinfobi22210.azurecr.io" # Nom du registy
  IMAGE_NAME: "be-ud" # Nom de votre image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Se connecter à la registry Azure
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REG_NAME }} \
            --username ${{ secrets.REGISTRY_USERNAME }} \
            --password-stdin

      - name: Construire l'image Docker
        run: |
          docker build -t ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ./src/backend

      - name: Pousser l'image sur la registry
        run: |
          docker push ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
